/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.codat.sync_for_expenses.models.operations;

import io.codat.sync_for_expenses.utils.Utils;
import java.io.InputStream;
import java.net.http.HttpResponse;
import java.util.Optional;


public class UpdateCustomerResponse {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * The request made is not valid.
     */
    private Optional<? extends io.codat.sync_for_expenses.models.shared.ErrorMessage> errorMessage;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Success
     */
    private Optional<? extends io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse> updateCustomerResponse;

    public UpdateCustomerResponse(
            String contentType,
            Optional<? extends io.codat.sync_for_expenses.models.shared.ErrorMessage> errorMessage,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse> updateCustomerResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(errorMessage, "errorMessage");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(updateCustomerResponse, "updateCustomerResponse");
        this.contentType = contentType;
        this.errorMessage = errorMessage;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.updateCustomerResponse = updateCustomerResponse;
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return contentType;
    }

    /**
     * The request made is not valid.
     */
    public Optional<? extends io.codat.sync_for_expenses.models.shared.ErrorMessage> errorMessage() {
        return errorMessage;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Success
     */
    public Optional<? extends io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse> updateCustomerResponse() {
        return updateCustomerResponse;
    }
    
    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public UpdateCustomerResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * The request made is not valid.
     */
    public UpdateCustomerResponse withErrorMessage(io.codat.sync_for_expenses.models.shared.ErrorMessage errorMessage) {
        Utils.checkNotNull(errorMessage, "errorMessage");
        this.errorMessage = Optional.ofNullable(errorMessage);
        return this;
    }
    
    /**
     * The request made is not valid.
     */
    public UpdateCustomerResponse withErrorMessage(Optional<? extends io.codat.sync_for_expenses.models.shared.ErrorMessage> errorMessage) {
        Utils.checkNotNull(errorMessage, "errorMessage");
        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public UpdateCustomerResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public UpdateCustomerResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Success
     */
    public UpdateCustomerResponse withUpdateCustomerResponse(io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse updateCustomerResponse) {
        Utils.checkNotNull(updateCustomerResponse, "updateCustomerResponse");
        this.updateCustomerResponse = Optional.ofNullable(updateCustomerResponse);
        return this;
    }
    
    /**
     * Success
     */
    public UpdateCustomerResponse withUpdateCustomerResponse(Optional<? extends io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse> updateCustomerResponse) {
        Utils.checkNotNull(updateCustomerResponse, "updateCustomerResponse");
        this.updateCustomerResponse = updateCustomerResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateCustomerResponse other = (UpdateCustomerResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.errorMessage, other.errorMessage) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            java.util.Objects.deepEquals(this.updateCustomerResponse, other.updateCustomerResponse);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            errorMessage,
            statusCode,
            rawResponse,
            updateCustomerResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateCustomerResponse.class,
                "contentType", contentType,
                "errorMessage", errorMessage,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "updateCustomerResponse", updateCustomerResponse);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Optional<? extends io.codat.sync_for_expenses.models.shared.ErrorMessage> errorMessage = Optional.empty();
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse> updateCustomerResponse = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * The request made is not valid.
         */
        public Builder errorMessage(io.codat.sync_for_expenses.models.shared.ErrorMessage errorMessage) {
            Utils.checkNotNull(errorMessage, "errorMessage");
            this.errorMessage = Optional.ofNullable(errorMessage);
            return this;
        }
        
        /**
         * The request made is not valid.
         */
        public Builder errorMessage(Optional<? extends io.codat.sync_for_expenses.models.shared.ErrorMessage> errorMessage) {
            Utils.checkNotNull(errorMessage, "errorMessage");
            this.errorMessage = errorMessage;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Success
         */
        public Builder updateCustomerResponse(io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse updateCustomerResponse) {
            Utils.checkNotNull(updateCustomerResponse, "updateCustomerResponse");
            this.updateCustomerResponse = Optional.ofNullable(updateCustomerResponse);
            return this;
        }
        
        /**
         * Success
         */
        public Builder updateCustomerResponse(Optional<? extends io.codat.sync_for_expenses.models.shared.UpdateCustomerResponse> updateCustomerResponse) {
            Utils.checkNotNull(updateCustomerResponse, "updateCustomerResponse");
            this.updateCustomerResponse = updateCustomerResponse;
            return this;
        }        
        
        public UpdateCustomerResponse build() {
            return new UpdateCustomerResponse(
                contentType,
                errorMessage,
                statusCode,
                rawResponse,
                updateCustomerResponse);
        }
    }
}

