/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.codat.lending.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.codat.lending.models.shared.AccountingBillPayment;
import io.codat.lending.utils.Response;
import io.codat.lending.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetAccountingBillPaymentResponse implements Response {

    /**
     * Success
     */
    private JsonNullable<? extends AccountingBillPayment> accountingBillPayment;

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public GetAccountingBillPaymentResponse(
            JsonNullable<? extends AccountingBillPayment> accountingBillPayment,
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(accountingBillPayment, "accountingBillPayment");
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.accountingBillPayment = accountingBillPayment;
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public GetAccountingBillPaymentResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(JsonNullable.undefined(), contentType, statusCode, rawResponse);
    }

    /**
     * Success
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<AccountingBillPayment> accountingBillPayment() {
        return (JsonNullable<AccountingBillPayment>) accountingBillPayment;
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Success
     */
    public GetAccountingBillPaymentResponse withAccountingBillPayment(AccountingBillPayment accountingBillPayment) {
        Utils.checkNotNull(accountingBillPayment, "accountingBillPayment");
        this.accountingBillPayment = JsonNullable.of(accountingBillPayment);
        return this;
    }

    /**
     * Success
     */
    public GetAccountingBillPaymentResponse withAccountingBillPayment(JsonNullable<? extends AccountingBillPayment> accountingBillPayment) {
        Utils.checkNotNull(accountingBillPayment, "accountingBillPayment");
        this.accountingBillPayment = accountingBillPayment;
        return this;
    }

    /**
     * HTTP response content type for this operation
     */
    public GetAccountingBillPaymentResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetAccountingBillPaymentResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetAccountingBillPaymentResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAccountingBillPaymentResponse other = (GetAccountingBillPaymentResponse) o;
        return 
            Objects.deepEquals(this.accountingBillPayment, other.accountingBillPayment) &&
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            accountingBillPayment,
            contentType,
            statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAccountingBillPaymentResponse.class,
                "accountingBillPayment", accountingBillPayment,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }
    
    public final static class Builder {
 
        private JsonNullable<? extends AccountingBillPayment> accountingBillPayment = JsonNullable.undefined();
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Success
         */
        public Builder accountingBillPayment(AccountingBillPayment accountingBillPayment) {
            Utils.checkNotNull(accountingBillPayment, "accountingBillPayment");
            this.accountingBillPayment = JsonNullable.of(accountingBillPayment);
            return this;
        }

        /**
         * Success
         */
        public Builder accountingBillPayment(JsonNullable<? extends AccountingBillPayment> accountingBillPayment) {
            Utils.checkNotNull(accountingBillPayment, "accountingBillPayment");
            this.accountingBillPayment = accountingBillPayment;
            return this;
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }
        
        public GetAccountingBillPaymentResponse build() {
            return new GetAccountingBillPaymentResponse(
                accountingBillPayment,
                contentType,
                statusCode,
                rawResponse);
        }
    }
}

