/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.codat.platform.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.codat.platform.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.util.Optional;

/**
 * SupplementalDataSourceConfiguration - The client's defined name for the object.
 */

public class SupplementalDataSourceConfiguration {

    /**
     * The underlying endpoint of the source system which the configuration is targeting. 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dataSource")
    private Optional<? extends String> dataSource;

    /**
     * The additional properties that are required when pulling records.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pullData")
    private Optional<? extends java.util.Map<String, String>> pullData;

    /**
     * The additional properties that are required to create and/or update records.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pushData")
    private Optional<? extends java.util.Map<String, String>> pushData;

    public SupplementalDataSourceConfiguration(
            @JsonProperty("dataSource") Optional<? extends String> dataSource,
            @JsonProperty("pullData") Optional<? extends java.util.Map<String, String>> pullData,
            @JsonProperty("pushData") Optional<? extends java.util.Map<String, String>> pushData) {
        Utils.checkNotNull(dataSource, "dataSource");
        Utils.checkNotNull(pullData, "pullData");
        Utils.checkNotNull(pushData, "pushData");
        this.dataSource = dataSource;
        this.pullData = pullData;
        this.pushData = pushData;
    }

    /**
     * The underlying endpoint of the source system which the configuration is targeting. 
     */
    public Optional<? extends String> dataSource() {
        return dataSource;
    }

    /**
     * The additional properties that are required when pulling records.
     */
    public Optional<? extends java.util.Map<String, String>> pullData() {
        return pullData;
    }

    /**
     * The additional properties that are required to create and/or update records.
     */
    public Optional<? extends java.util.Map<String, String>> pushData() {
        return pushData;
    }
    
    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The underlying endpoint of the source system which the configuration is targeting. 
     */
    public SupplementalDataSourceConfiguration withDataSource(String dataSource) {
        Utils.checkNotNull(dataSource, "dataSource");
        this.dataSource = Optional.ofNullable(dataSource);
        return this;
    }
    
    /**
     * The underlying endpoint of the source system which the configuration is targeting. 
     */
    public SupplementalDataSourceConfiguration withDataSource(Optional<? extends String> dataSource) {
        Utils.checkNotNull(dataSource, "dataSource");
        this.dataSource = dataSource;
        return this;
    }

    /**
     * The additional properties that are required when pulling records.
     */
    public SupplementalDataSourceConfiguration withPullData(java.util.Map<String, String> pullData) {
        Utils.checkNotNull(pullData, "pullData");
        this.pullData = Optional.ofNullable(pullData);
        return this;
    }
    
    /**
     * The additional properties that are required when pulling records.
     */
    public SupplementalDataSourceConfiguration withPullData(Optional<? extends java.util.Map<String, String>> pullData) {
        Utils.checkNotNull(pullData, "pullData");
        this.pullData = pullData;
        return this;
    }

    /**
     * The additional properties that are required to create and/or update records.
     */
    public SupplementalDataSourceConfiguration withPushData(java.util.Map<String, String> pushData) {
        Utils.checkNotNull(pushData, "pushData");
        this.pushData = Optional.ofNullable(pushData);
        return this;
    }
    
    /**
     * The additional properties that are required to create and/or update records.
     */
    public SupplementalDataSourceConfiguration withPushData(Optional<? extends java.util.Map<String, String>> pushData) {
        Utils.checkNotNull(pushData, "pushData");
        this.pushData = pushData;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SupplementalDataSourceConfiguration other = (SupplementalDataSourceConfiguration) o;
        return 
            java.util.Objects.deepEquals(this.dataSource, other.dataSource) &&
            java.util.Objects.deepEquals(this.pullData, other.pullData) &&
            java.util.Objects.deepEquals(this.pushData, other.pushData);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            dataSource,
            pullData,
            pushData);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SupplementalDataSourceConfiguration.class,
                "dataSource", dataSource,
                "pullData", pullData,
                "pushData", pushData);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> dataSource = Optional.empty();
 
        private Optional<? extends java.util.Map<String, String>> pullData = Optional.empty();
 
        private Optional<? extends java.util.Map<String, String>> pushData = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The underlying endpoint of the source system which the configuration is targeting. 
         */
        public Builder dataSource(String dataSource) {
            Utils.checkNotNull(dataSource, "dataSource");
            this.dataSource = Optional.ofNullable(dataSource);
            return this;
        }
        
        /**
         * The underlying endpoint of the source system which the configuration is targeting. 
         */
        public Builder dataSource(Optional<? extends String> dataSource) {
            Utils.checkNotNull(dataSource, "dataSource");
            this.dataSource = dataSource;
            return this;
        }

        /**
         * The additional properties that are required when pulling records.
         */
        public Builder pullData(java.util.Map<String, String> pullData) {
            Utils.checkNotNull(pullData, "pullData");
            this.pullData = Optional.ofNullable(pullData);
            return this;
        }
        
        /**
         * The additional properties that are required when pulling records.
         */
        public Builder pullData(Optional<? extends java.util.Map<String, String>> pullData) {
            Utils.checkNotNull(pullData, "pullData");
            this.pullData = pullData;
            return this;
        }

        /**
         * The additional properties that are required to create and/or update records.
         */
        public Builder pushData(java.util.Map<String, String> pushData) {
            Utils.checkNotNull(pushData, "pushData");
            this.pushData = Optional.ofNullable(pushData);
            return this;
        }
        
        /**
         * The additional properties that are required to create and/or update records.
         */
        public Builder pushData(Optional<? extends java.util.Map<String, String>> pushData) {
            Utils.checkNotNull(pushData, "pushData");
            this.pushData = pushData;
            return this;
        }
        
        public SupplementalDataSourceConfiguration build() {
            return new SupplementalDataSourceConfiguration(
                dataSource,
                pullData,
                pushData);
        }
    }
}

