/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.codat.lending.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * BillStatus - Current state of the bill.
 */
public enum BillStatus {
    UNKNOWN("Unknown"),
    OPEN("Open"),
    PARTIALLY_PAID("PartiallyPaid"),
    PAID("Paid"),
    VOID("Void"),
    DRAFT("Draft");

    @JsonValue
    private final String value;

    private BillStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<BillStatus> fromValue(String value) {
        for (BillStatus o: BillStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
