workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    accounting-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Accounting.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/accounting-source
    bank-feeds-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Bank-Feeds.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/bank-feeds-source
    banking-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Banking.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/banking-source
    lending-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Lending.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/lending-source
    platform-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/platform-source
    sync-for-commerce-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-source
    sync-for-expenses-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-source
    sync-for-payables-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-source
    sync-for-payroll-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payroll.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payroll-source
targets:
    accounting-library:
        target: java
        source: accounting-source
        output: previous-versions/accounting
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/accounting-source-code-samples
            blocking: false
    bank-feeds-library:
        target: java
        source: bank-feeds-source
        output: bank-feeds
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/bank-feeds-source-code-samples
            blocking: false
    banking-library:
        target: java
        source: banking-source
        output: previous-versions/banking
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/banking-source-code-samples
            blocking: false
    lending-library:
        target: java
        source: lending-source
        output: lending
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/lending-source-code-samples
            blocking: false
    platform-library:
        target: java
        source: platform-source
        output: platform
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/platform-source-code-samples
            blocking: false
    sync-for-commerce-library:
        target: java
        source: sync-for-commerce-source
        output: sync-for-commerce
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-source-code-samples
            blocking: false
    sync-for-expenses-library:
        target: java
        source: sync-for-expenses-source
        output: sync-for-expenses
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-source-code-samples
            blocking: false
    sync-for-payables-library:
        target: java
        source: sync-for-payables-source
        output: sync-for-payables
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-source-code-samples
            blocking: false
    sync-for-payroll-library:
        target: java
        source: sync-for-payroll-source
        output: sync-for-payroll
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payroll-source-code-samples
            blocking: false
