/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.codat.accounting.models.operations;

import io.codat.accounting.utils.Options;
import io.codat.accounting.utils.RetryConfig;
import io.codat.accounting.utils.Utils;
import java.util.Optional;

public class UploadDirectIncomeAttachmentRequestBuilder {

    private UploadDirectIncomeAttachmentRequest request;
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUploadDirectIncomeAttachment sdk;

    public UploadDirectIncomeAttachmentRequestBuilder(SDKMethodInterfaces.MethodCallUploadDirectIncomeAttachment sdk) {
        this.sdk = sdk;
    }

    public UploadDirectIncomeAttachmentRequestBuilder request(io.codat.accounting.models.operations.UploadDirectIncomeAttachmentRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public UploadDirectIncomeAttachmentRequestBuilder retryConfig(io.codat.accounting.utils.RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public UploadDirectIncomeAttachmentRequestBuilder retryConfig(java.util.Optional<io.codat.accounting.utils.RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }

    public UploadDirectIncomeAttachmentResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
                                                    .retryConfig(retryConfig)
                                                    .build());
        return sdk.uploadAttachment(
            request,
            options);
    }
}
